Repository Team-BomBomBom/Server, pull requests merged in 2024-10, with the labels that each got.

#66 Feat: #BBB-145 내가 만든 스터디 목록 API
  app/external-api/src/main/java/com/bombombom/devs/external/study/controller/StudyController.java
  app/external-api/src/main/java/com/bombombom/devs/external/study/service/StudyService.java
  app/external-api/src/test/java/com/bombombom/devs/external/study/StudyIntegrationTest.java
  domain/src/main/java/com/bombombom/devs/study/repository/StudyRepository.java
Labels: ✅Test, ⚙️Build

#51 Feat: #BBB-120 알고리즘 과제 할당 및 해결 여부 요청에 Rate Limit과 대기열 시스템 적용
  .github/workflows/gradle.yml
  app/external-api/build.gradle
  app/external-api/src/main/java/com/bombombom/devs/external/algo/service/AlgorithmProblemQueueService.java
  app/external-api/src/main/java/com/bombombom/devs/external/algo/service/dto/command/AssignAlgorithmProblemCommand.java
  app/external-api/src/main/java/com/bombombom/devs/external/algo/service/dto/command/UpdateAlgorithmTaskStatusCommand.java
  app/external-api/src/main/java/com/bombombom/devs/external/algo/service/dto/result/AlgorithmProblemSolvedHistoryResult.java
  app/external-api/src/main/java/com/bombombom/devs/external/algo/service/dto/result/AlgorithmTaskUpdateStatusResult.java
  app/external-api/src/main/java/com/bombombom/devs/external/study/controller/StudyController.java
  app/external-api/src/main/java/com/bombombom/devs/external/study/controller/dto/request/CheckAlgorithmProblemSolvedRequest.java
  app/external-api/src/main/java/com/bombombom/devs/external/study/controller/dto/response/AlgorithmStudyProgressResponse.java
  app/external-api/src/main/java/com/bombombom/devs/external/study/controller/dto/response/AlgorithmStudyTaskStatusResponse.java
  app/external-api/src/main/java/com/bombombom/devs/external/study/service/AlgorithmStudyService.java
  app/external-api/src/main/java/com/bombombom/devs/external/study/service/StudyService.java
  app/external-api/src/main/java/com/bombombom/devs/external/study/service/dto/command/CheckAlgorithmProblemSolvedCommand.java
  app/external-api/src/main/java/com/bombombom/devs/external/study/service/dto/result/SolvedAlgorithmProblemResult.java
  app/external-api/src/main/java/com/bombombom/devs/external/study/service/dto/result/progress/AlgorithmStudyProgress.java
  app/external-api/src/main/java/com/bombombom/devs/job/AlgorithmStudyAssignmentJob.java
  app/external-api/src/main/java/com/bombombom/devs/job/QuartzJobScheduler.java
  app/external-api/src/main/java/com/bombombom/devs/ratelimit/ApiRateLimiter.java
  app/external-api/src/main/java/com/bombombom/devs/ratelimit/config/SolvedacApiRateLimitConfig.java
  app/external-api/src/test/java/com/bombombom/devs/external/study/StudyIntegrationTest.java
  app/external-api/src/test/java/com/bombombom/devs/external/study/controller/StudyControllerTest.java
  app/external-api/src/test/java/com/bombombom/devs/external/study/service/StudyServiceTest.java
  core/src/main/java/com/bombombom/devs/core/exception/ErrorCode.java
  core/src/main/java/com/bombombom/devs/core/exception/RateLimitException.java
  domain/build.gradle
  domain/src/main/java/com/bombombom/devs/algo/constant/AlgorithmProblemRedisConstant.java
  domain/src/main/java/com/bombombom/devs/algo/enums/AlgorithmProblemRequestType.java
  domain/src/main/java/com/bombombom/devs/algo/model/vo/AlgorithmProblemQueueMessage.java
  domain/src/main/java/com/bombombom/devs/algo/model/vo/AlgorithmTaskUpdateStatus.java
  domain/src/main/java/com/bombombom/devs/algo/model/vo/AssignAlgorithmProblem.java
  domain/src/main/java/com/bombombom/devs/algo/model/vo/PendingMessageInfo.java
  domain/src/main/java/com/bombombom/devs/algo/model/vo/UpdateAlgorithmTaskStatus.java
  domain/src/main/java/com/bombombom/devs/algo/repository/AlgorithmAssignmentRateLimitRepository.java
  domain/src/main/java/com/bombombom/devs/algo/repository/AlgorithmProblemRedisQueueRepository.java
  domain/src/main/java/com/bombombom/devs/algo/repository/AlgorithmProblemRepository.java
  domain/src/main/java/com/bombombom/devs/config/RedisConfiguration.java
  domain/src/main/java/com/bombombom/devs/config/TokenBucketConfig.java
  domain/src/main/java/com/bombombom/devs/study/model/AlgorithmProblemAssignment.java
  domain/src/main/java/com/bombombom/devs/study/model/AlgorithmProblemSolvedHistory.java
  domain/src/main/java/com/bombombom/devs/study/repository/AlgorithmProblemSolveHistoryRepository.java
  domain/src/main/java/com/bombombom/devs/study/repository/AlgorithmProblemSolvedHistoryRepository.java
  domain/src/main/resources/application.yml
  domain/src/test/java/com/bombombom/devs/study/AlgorithmProblemAssignmentSolveHistoryTest.java
  domain/src/test/java/com/bombombom/devs/study/AlgorithmProblemAssignmentTest.java
  support/solvedac-client/src/main/java/com/bombombom/devs/solvedac/SolvedacClient.java
Labels: ✨Feat

#70 [BBB-148] ⚡️Fix: ElastiCache 연결 수립 실패 문제 해결
  .github/workflows/gradle.yml
  domain/src/main/java/com/bombombom/devs/config/RedisConfiguration.java
  domain/src/main/resources/application.yml
Labels: ⚡️Fix

#71 Revert "[BBB-148] ⚡️Fix: ElastiCache 연결 수립 실패 문제 해결" & 다른 방식으로 TLS 연결 설정
  .github/workflows/gradle.yml
  domain/src/main/java/com/bombombom/devs/config/RedisConfiguration.java
  domain/src/main/resources/application.yml
Labels: ⚡️Fix

#72 [BBB-149] Fix: Token Bucket을 관리하는 ProxyManager 사용 중에 NoSuchMethodError가 발생하는 문제
  app/external-api/build.gradle
  domain/build.gradle
  domain/src/main/java/com/bombombom/devs/config/TokenBucketConfig.java
Labels: ⚡️Fix

#57 Feat: #BBB-136 로그인 및 회원가입 시 클라이언트와 서버 간 종단간 암호화 적용
  app/external-api/build.gradle
  app/external-api/src/main/java/com/bombombom/devs/external/encryption/controller/EncryptionController.java
  app/external-api/src/main/java/com/bombombom/devs/external/encryption/controller/dto/AddInMemoryAsymmetricKeyRequest.java
  app/external-api/src/main/java/com/bombombom/devs/external/encryption/controller/dto/ProvidePublicKeyResponse.java
  app/external-api/src/main/java/com/bombombom/devs/external/encryption/service/AsymmetricEncryptionService.java
  app/external-api/src/main/java/com/bombombom/devs/external/encryption/service/dto/AsymmetricKeyResult.java
  app/external-api/src/main/java/com/bombombom/devs/external/encryption/service/dto/PublicKeyResult.java
  app/external-api/src/main/java/com/bombombom/devs/external/encryption/service/dto/SymmetricKeyResult.java
  app/external-api/src/main/java/com/bombombom/devs/external/global/circuitbreaker/CircuitBreakerProperty.java
  app/external-api/src/main/java/com/bombombom/devs/external/global/circuitbreaker/CircuitBreakerProvider.java
  app/external-api/src/main/java/com/bombombom/devs/external/global/circuitbreaker/RetryProvider.java
  app/external-api/src/main/java/com/bombombom/devs/external/global/circuitbreaker/config/Resilience4jOrderConfig.java
  app/external-api/src/main/java/com/bombombom/devs/external/global/decryption/DecryptedRequestWrapper.java
  app/external-api/src/main/java/com/bombombom/devs/external/global/decryption/DecryptionFilter.java
  app/external-api/src/main/java/com/bombombom/devs/external/global/decryption/DecryptionFilterConfig.java
  app/external-api/src/main/java/com/bombombom/devs/external/global/decryption/EncryptionManager.java
  app/external-api/src/main/java/com/bombombom/devs/external/global/decryption/InMemoryAsymmetricKeyManager.java
  app/external-api/src/main/java/com/bombombom/devs/external/global/decryption/dto/EncryptedRequest.java
  app/external-api/src/main/java/com/bombombom/devs/external/global/security/config/PasswordConfig.java
  app/external-api/src/main/java/com/bombombom/devs/external/global/web/config/WebConfig.java
  app/external-api/src/test/java/com/bombombom/devs/external/encryption/EncryptionTest.java
  core/src/main/java/com/bombombom/devs/core/exception/ErrorCode.java
  core/src/main/java/com/bombombom/devs/core/util/encryption/AESEncryption.java
  core/src/main/java/com/bombombom/devs/core/util/encryption/AsymmetricKeyEncryption.java
  core/src/main/java/com/bombombom/devs/core/util/encryption/ECCEncryption.java
  core/src/main/java/com/bombombom/devs/core/util/encryption/RSAEncryption.java
  core/src/main/java/com/bombombom/devs/core/util/encryption/SymmetricKeyEncryption.java
  domain/src/main/java/com/bombombom/devs/common/constant/EncryptionRedisConstant.java
  domain/src/main/java/com/bombombom/devs/config/RedisConfiguration.java
  domain/src/main/java/com/bombombom/devs/encryption/model/AsymmetricKey.java
  domain/src/main/java/com/bombombom/devs/encryption/model/vo/PrivateKeyInfo.java
  domain/src/main/java/com/bombombom/devs/encryption/model/vo/PublicKeyInfo.java
  domain/src/main/java/com/bombombom/devs/encryption/repository/AsymmetricEncryptionRedisRepository.java
  domain/src/main/java/com/bombombom/devs/encryption/repository/AsymmetricKeyRepository.java
  domain/src/main/resources/application.yml
Labels: ✨Feat
